export enum SourceFiles {
    FUELLUNGSGRAD_SPEICHERSEEN = 'kpi-strom-11_fuellstand-speicherseen_ch-gesamt.csv',
    STROM_FUELLUNGSGRAD_SPEICHERSEEN_V2 = 'kpi-strom-11_fuellstand-speicherseen_ch-gesamt-v2.csv',
    FUELLSTAND_GASSPEICHER = 'kpi-gas-7_fuellstand-gasspeicher_viz.csv',
    GAS_FUELLSTAND_GASSPEICHER_V2 = 'kpi-gas-7_fuellstand-gasspeicher_viz_v2.csv',
    STROM_IMPORT_EXPORT_HISTORICAL_VALUES = 'kpi-strom-9_import-export_hist.csv',
    STROM_IMPORT_EXPORT_HISTORICAL_VALUES_V2 = 'kpi-strom-9_import-export_hist_V2.csv',
    STROM_IMPORT_EXPORT_NETTO = 'kpi-strom-9_import-export_netto.csv',
    STROM_IMPORT_EXPORT_UEBERSICHT = 'kpi-strom-9_import-export_uebersicht.csv',
    DYNAMIC_TRANSLATIONS = 'dynamic_translation.json',
    AMPEL = 'config_ampel.json',
    GAS_IMPORT_KARTE = 'kpi-gas-5_import_karte.csv',
    GAS_IMPORT_HISTORICAL_VALUES = 'kpi-gas-5_import_netto-monat-vsg.csv',
    GAS_IMPORT_HISTORICAL_VALUES_V2 = 'kpi-gas-5_import_netto-monat-vsg-v2.csv',
    STROM_PRODUKTIONSMIX = 'kpi-strom-5_produktion_strommix-donut-mars.csv',
    STROM_PRODUKTION_IMPORT_VERBRAUCH = 'kpi-strom-5_produktion_import-verbrauch-mars.csv',
    STROM_VERBRAUCH_HISTORICAL_VALUES = 'kpi-strom-1_landesverbrauch_SG.csv',
    STROM_VERBRAUCH_LANDESVERBRAUCH_MIT_PROGNOSE_V2 = 'kpi-strom-1_landesverbrauch_SG_V2.csv',
    STROM_VERBRAUCH_ENDVERBRAUCH = 'kpi-strom-1_landesverbrauch_endverbrauch_SG.csv',
    STROM_VERBRAUCH_ENDVERBRAUCH_V2 = 'kpi-strom-1_landesverbrauch_endverbrauch_SG_V2.csv',
    STROM_VERBRAUCH_LANDESVERBRAUCH = 'kpi-strom-1_landesverbrauch_BFE-SG-ENTSOE.csv',
    STROM_VERBRAUCH_LANDESVERBRAUCH_VERGLEICH_V2 = 'kpi-strom-1_landesverbrauch_BFE-SG-ENTSOE_V2.csv',
    STROM_SPARZIEL_ZIEL = 'kpi-strom-3_sparziel_ziel.csv',
    STROM_SPARZIEL_ZIEL_V4 = 'kpi-strom-3_sparziel_ziel_V4.csv',
    STROM_SPARZIEL_AKTUELLE_EINSPARUNG = 'kpi-strom-3_sparziel_aktuelle_einsparung.csv',
    STROM_SPARZIEL_AKTUELLE_EINSPARUNG_V2 = 'kpi-strom-3_sparziel_aktuelle_einsparung_V2.csv',
    STROM_SPARZIEL_AKTUELLE_EINSPARUNG_V4 = 'kpi-strom-3_sparziel_aktuelle_einsparung_V4.csv',
    STROM_SPARZIEL_EINSPARUNG_PRO_MONAT_KUNDENGRUPPE = 'kpi-strom-3_monatliche_einsparung_kundengruppen.csv',
    STROM_SPARZIEL_EINSPARUNG_AKTUELLER_MONAT_KUNDENGRUPPE = 'kpi-strom-3_taegliche_einsparung_kundengruppen.csv',
    STROM_SPARZIEL_ZIEL_AKTUELLER_MONAT_KUNDENGRUPPE = 'kpi-strom-3_aktueller_monat_einsparung_kundengruppen.csv',
    STROM_SPARZIEL_5_PROZENT_PEAK_H = 'kpi-strom-3-sparziel5_peak_h_visualisierung.csv',
    STROM_SPARZIEL_5_PROZENT_EINSPARUNGEN = 'kpi-strom-3-sparziel5_einsparungen_pro_periode.csv',
    STROM_KKW_PRODUKTION_CH_V1 = 'kpi-strom-6_kkw_produktion_CH_V1.csv',
    STROM_KKW_PRODUKTION_FR_V1 = 'kpi-strom-6_kkw_produktion_FR_V1.csv',
    STROM_KKW_PRODUKTION_AUSFAELLE_V1 = 'kpi-strom-6_kkw-outages.csv',
    STROM_KKW_PRODUKTION_VERFUEGBARKEIT = 'kpi-strom-6_kkw-availability.csv',
    GAS_SPARZIEL_ZIEL = 'kpi-gas-3_gassparziel_ziel.csv',
    GAS_SPARZIEL_ZIEL_V2 = 'kpi-gas-3_gassparziel_ziel-v2.csv',
    GAS_SPARZIEL_ZIEL_V4 = 'kpi-gas-3_gassparziel_ziel_V4.csv',
    GAS_SPARZIEL_AKTUELLE_EINSPARUNG = 'kpi-gas-3_gassparziel_aktuelle_einsparung.csv',
    GAS_SPARZIEL_AKTUELLE_EINSPARUNG_V2 = 'kpi-gas-3_gassparziel_aktuelle_einsparung-v2.csv',
    GAS_SPARZIEL_AKTUELLE_EINSPARUNG_V3 = 'kpi-gas-3_gassparziel_aktuelle_einsparung_V3.csv',
    GAS_SPARZIEL_AKTUELLE_EINSPARUNG_V4 = 'kpi-gas-3_gassparziel_aktuelle_einsparung_V4.csv',
    SPARTIPPS = 'kpi-spartipps.csv',
    SPARTIPPS_V2 = 'kpi-spartipps_V2.csv',
    PREISE_TREIBSTOFF_BLEIFREI = 'kpi-preise-1_treibstoff_benzin.csv',
    PREISE_TREIBSTOFF_DIESEL = 'kpi-preise-1_treibstoff_diesel.csv',
    PREISE_GAS_BOERSE = 'kpi-preise-3_gas_boerse.csv',
    PREISE_GAS_DAYAHEAD = 'kpi-preise-3_gas_ttf_dayahead.csv',
    PREISE_GAS_ENDVERBRAUCH = 'kpi-preise-3_gas_endverbrauch.csv',
    PREISE_GAS_FUTURES = 'kpi-preise-3_gas_ttf_futures.csv',
    PREISE_HEIZOEL_ENTWICKLUNG = 'kpi-preise-4_heizol_entwicklung.csv',
    PREISE_STROM_BOERSE = 'kpi-preise-5_strom_boerse.csv',
    PREISE_STROM_ENDVERBRAUCH = 'kpi-preise-5_strom_endverbrauch.csv',
    PREISE_STROM_FUTURES = 'kpi-preise-5_strom_futures.csv',
    PREISE_BRENNHOLZ_ENDVERBRAUCH = 'kpi-preise-6_brennholz_endverbrauch.csv',
    PREISE_FERNWAERME_ENDVERBRAUCH = 'kpi-preise-7_fernwaerme_endverbrauch.csv',
    WETTER_TEMPERATUR_AKTUELL = 'kpi-wetter-1_meteoswiss_temp_aktuell.csv',
    WETTER_TEMPERATUR_PROGNOSE = 'kpi-wetter-1_meteoswiss_temp_prognose.csv',
    WETTER_TEMPERATUR_TREND = 'kpi-wetter-1_meteoswiss_trend.csv',
    WETTER_TEMPERATUR_TREND_V2 = 'kpi-wetter-1_meteoswiss_trend_V2.csv',
    WETTER_NIEDERSCHLAG = 'kpi-wetter-3_meteoswiss_niederschlag_V1.csv',
    WETTER_SCHNEERESERVEN = 'kpi-wetter-4_slf_schneewasser_V1.csv',
}

export const RoutingFunctions: { [key in SourceFiles]: string } = {
    [SourceFiles.FUELLUNGSGRAD_SPEICHERSEEN]: `data-processing-fuellungsgrad-speicherseen`,
    [SourceFiles.STROM_FUELLUNGSGRAD_SPEICHERSEEN_V2]: `data-processing-fuellungsgrad-speicherseen-v2`,
    [SourceFiles.FUELLSTAND_GASSPEICHER]: 'data-processing-fuellstand-gasspeicher',
    [SourceFiles.GAS_FUELLSTAND_GASSPEICHER_V2]: 'data-processing-fuellstand-gasspeicher-v2',
    [SourceFiles.STROM_IMPORT_EXPORT_HISTORICAL_VALUES]: 'data-processing-strom-import-export-historical-values',
    [SourceFiles.STROM_IMPORT_EXPORT_HISTORICAL_VALUES_V2]: 'data-processing-strom-import-export-historical-values-v2',
    [SourceFiles.STROM_IMPORT_EXPORT_NETTO]: 'data-processing-strom-import-export-netto',
    [SourceFiles.STROM_IMPORT_EXPORT_UEBERSICHT]: 'data-processing-strom-import-export-uebersicht',
    [SourceFiles.DYNAMIC_TRANSLATIONS]: 'data-processing-dynamic-translations',
    [SourceFiles.AMPEL]: 'data-processing-ampel',
    [SourceFiles.GAS_IMPORT_KARTE]: 'data-processing-gas-import-karte',
    [SourceFiles.GAS_IMPORT_HISTORICAL_VALUES]: 'data-processing-gas-import-historical-values',
    [SourceFiles.GAS_IMPORT_HISTORICAL_VALUES_V2]: 'data-processing-gas-import-historical-values-v2',
    [SourceFiles.STROM_PRODUKTIONSMIX]: 'data-processing-strom-produktionsmix',
    [SourceFiles.STROM_PRODUKTION_IMPORT_VERBRAUCH]: 'data-processing-strom-produktion-import-verbrauch',
    [SourceFiles.STROM_VERBRAUCH_HISTORICAL_VALUES]: 'data-processing-strom-verbrauch-historical-values',
    [SourceFiles.STROM_VERBRAUCH_LANDESVERBRAUCH_MIT_PROGNOSE_V2]: 'data-processing-landesverbrauch-prognose-v2',
    [SourceFiles.STROM_VERBRAUCH_ENDVERBRAUCH]: 'data-processing-strom-verbrauch-endverbrauch',
    [SourceFiles.STROM_VERBRAUCH_ENDVERBRAUCH_V2]: 'data-processing-strom-verbrauch-endverbrauch-v2',
    [SourceFiles.STROM_VERBRAUCH_LANDESVERBRAUCH]: 'data-processing-strom-verbrauch-landesverbrauch',
    [SourceFiles.STROM_VERBRAUCH_LANDESVERBRAUCH_VERGLEICH_V2]: 'data-processing-strom-landesverbrauch-vergleich-v2',
    [SourceFiles.STROM_SPARZIEL_ZIEL]: 'data-processing-strom-sparziel-ziel',
    [SourceFiles.STROM_SPARZIEL_ZIEL_V4]: 'data-processing-strom-sparziel-ziel-v4',
    [SourceFiles.STROM_SPARZIEL_AKTUELLE_EINSPARUNG]: 'data-processing-strom-sparziel-aktuelle-einsparung',
    [SourceFiles.STROM_SPARZIEL_AKTUELLE_EINSPARUNG_V2]: 'data-processing-strom-sparziel-aktuelle-einsparung-v2',
    [SourceFiles.STROM_SPARZIEL_AKTUELLE_EINSPARUNG_V4]: 'data-processing-strom-sparziel-aktuelle-einsparung-v4',
    [SourceFiles.STROM_SPARZIEL_EINSPARUNG_PRO_MONAT_KUNDENGRUPPE]: 'data-processing-sparziel-pro-monat-kundengruppe',
    [SourceFiles.STROM_SPARZIEL_EINSPARUNG_AKTUELLER_MONAT_KUNDENGRUPPE]: 'data-processing-sparziel-aktueller-monat-kundengruppe',
    [SourceFiles.STROM_SPARZIEL_ZIEL_AKTUELLER_MONAT_KUNDENGRUPPE]: 'data-processing-sparziel-ziel-aktueller-monat-kundengruppe',
    [SourceFiles.STROM_SPARZIEL_5_PROZENT_PEAK_H]: 'data-processing-strom-sparziel-5-prozent-peak-h',
    [SourceFiles.STROM_SPARZIEL_5_PROZENT_EINSPARUNGEN]: 'data-processing-strom-sparziel-5-prozent-einsparungen',
    [SourceFiles.STROM_KKW_PRODUKTION_CH_V1]: 'data-processing-strom-kkw-produktion-ch-v1',
    [SourceFiles.STROM_KKW_PRODUKTION_FR_V1]: 'data-processing-strom-kkw-produktion-fr-v1',
    [SourceFiles.STROM_KKW_PRODUKTION_AUSFAELLE_V1]: 'data-processing-strom-kkw-ausfaelle-v1',
    [SourceFiles.STROM_KKW_PRODUKTION_VERFUEGBARKEIT]: 'data-processing-strom-kkw-verfuegbarkeit',
    [SourceFiles.GAS_SPARZIEL_ZIEL]: 'data-processing-gas-sparziel-ziel',
    [SourceFiles.GAS_SPARZIEL_ZIEL_V2]: 'data-processing-gas-sparziel-ziel-v2',
    [SourceFiles.GAS_SPARZIEL_ZIEL_V4]: 'data-processing-gas-sparziel-ziel-v4',
    [SourceFiles.GAS_SPARZIEL_AKTUELLE_EINSPARUNG]: 'data-processing-gas-sparziel-aktuelle-einsparung',
    [SourceFiles.GAS_SPARZIEL_AKTUELLE_EINSPARUNG_V2]: 'data-processing-gas-sparziel-aktuelle-einsparung-v2',
    [SourceFiles.GAS_SPARZIEL_AKTUELLE_EINSPARUNG_V3]: 'data-processing-gas-sparziel-aktuelle-einsparung-v3',
    [SourceFiles.GAS_SPARZIEL_AKTUELLE_EINSPARUNG_V4]: 'data-processing-gas-sparziel-aktuelle-einsparung-v4',
    [SourceFiles.SPARTIPPS]: 'data-processing-spartipps',
    [SourceFiles.SPARTIPPS_V2]: 'data-processing-spartipps-v2',
    [SourceFiles.PREISE_TREIBSTOFF_BLEIFREI]: 'data-processing-preise-treibstoff-bleifrei',
    [SourceFiles.PREISE_TREIBSTOFF_DIESEL]: 'data-processing-preise-treibstoff-diesel',
    [SourceFiles.PREISE_GAS_BOERSE]: 'data-processing-preise-gas-boerse',
    [SourceFiles.PREISE_GAS_ENDVERBRAUCH]: 'data-processing-preise-gas-endverbrauch',
    [SourceFiles.PREISE_GAS_DAYAHEAD]: 'data-processing-preise-gas-dayahead',
    [SourceFiles.PREISE_GAS_FUTURES]: 'data-processing-preise-gas-futures',
    [SourceFiles.PREISE_HEIZOEL_ENTWICKLUNG]: 'data-processing-preise-heizoel-entwicklung',
    [SourceFiles.PREISE_STROM_BOERSE]: 'data-processing-preise-strom-boerse',
    [SourceFiles.PREISE_STROM_ENDVERBRAUCH]: 'data-processing-preise-strom-endverbrauch',
    [SourceFiles.PREISE_STROM_FUTURES]: 'data-processing-preise-strom-futures',
    [SourceFiles.PREISE_BRENNHOLZ_ENDVERBRAUCH]: 'data-processing-preise-brennholz-endverbrauch',
    [SourceFiles.PREISE_FERNWAERME_ENDVERBRAUCH]: 'data-processing-preise-fernwaerme-endverbrauch',
    [SourceFiles.WETTER_TEMPERATUR_AKTUELL]: 'data-processing-wetter-temperatur-aktuell',
    [SourceFiles.WETTER_TEMPERATUR_PROGNOSE]: 'data-processing-wetter-temperatur-prognose',
    [SourceFiles.WETTER_TEMPERATUR_TREND]: 'data-processing-wetter-temperatur-trend',
    [SourceFiles.WETTER_TEMPERATUR_TREND_V2]: 'data-processing-wetter-temperatur-trend-v2',
    [SourceFiles.WETTER_NIEDERSCHLAG]: 'data-processing-wetter-niederschlag',
    [SourceFiles.WETTER_SCHNEERESERVEN]: 'data-processing-wetter-schneereserven'
};

export const ImagesProcessingFunction = 'data-processing-images';